yatube/about/urls.py
from django.urls import path
from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.new_post, name='new_post'),
    path('group/<slug:slug>/', views.group_posts, name='show_group_post'),
    path('<str:username>/', views.profile, name='profile'),
    path('<str:username>/<int:post_id>/', views.post_view, name='post'),
    path(
        '<str:username>/<int:post_id>/edit/',
        views.post_edit,
        name='post_edit'
    ),
]

yatube/users/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup')
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('', include('posts.urls')),
    path('about/', include('about.urls', namespace='about')),
]

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model
User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self) -> str:
        return self.title


class Post(models.Model):
    text = models.TextField(verbose_name='Текст',
                            help_text='Текст поста')
    pub_date = models.DateTimeField('date published', auto_now_add=True)
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='posts')
    group = models.ForeignKey(Group,
                              verbose_name='Группа',
                              help_text='Дайте короткое название группы',
                              on_delete=models.SET_NULL,
                              blank=True,
                              null=True,
                              related_name='posts')

    def __str__(self):
        return f'{self.author} | {self.text[:15]}'

    class Meta:
        ordering = ['-pub_date']

yatube/posts/forms.py
from posts.models import Post
from django.forms import ModelForm
from django.utils.translation import gettext_lazy as _


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ['text', 'group']
        labels = {
            'text': _('Текст'),
            'group': _('Группа'),
        }

yatube/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

yatube/about/views.py
from django.views.generic.base import TemplateView


class AboutAuthorView(TemplateView):
    template_name = 'about/author.html'


class AboutTechView(TemplateView):
    template_name = 'about/tech.html'

yatube/posts/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.conf import settings

from .models import Post, Group, User
from .forms import PostForm


def index(request):
    post_list = Post.objects.all()
    paginator = Paginator(post_list, settings.PAGINATOR_PER_PAGE_VAL)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    return render(
        request,
        'index.html',
        {'page': page}
    )


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    post_list = group.posts.all()
    paginator = Paginator(post_list, settings.PAGINATOR_PER_PAGE_VAL)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    return render(
        request,
        'group.html',
        {'group': group, 'page': page}
    )


@login_required
def new_post(request):
    form = PostForm()
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('index')
    return render(request, 'newpost.html', {'form': form})


def profile(request, username):
    user = get_object_or_404(User, username=username)
    posts = Post.objects.filter(author=user)
    paginator = Paginator(posts, settings.PAGINATOR_PER_PAGE_VAL)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    context = {
        'author': user,
        'page': page,
    }
    return render(request, 'profile.html', context)


def post_view(request, username, post_id):
    post = get_object_or_404(Post, pk=post_id, author__username=username)
    context = {
        'author': post.author,
        'post': post
    }
    return render(request, 'post.html', context)


@login_required
def post_edit(request, username, post_id):
    post = get_object_or_404(Post, pk=post_id, author__username=username)
    if request.user != post.author:
        return redirect('post', username=username, post_id=post_id)
    form = PostForm(request.POST or None, instance=post)
    if form.is_valid():
        form.save()
        return redirect(
            "post",
            username=request.user.username,
            post_id=post_id
        )
    return render(
        request, 'newpost.html', {'form': form, 'post': post},
    )

yatube/users/views.py
from django.views.generic import CreateView
from django.urls import reverse_lazy
from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('signup')
    template_name = 'signup.html'

yatube/about/templates/about/author.html
<!-- templates/about/author.html -->
{% extends "base.html" %}
{% block title %}Об авторе проекта{% endblock %}
{% block content %}
{% load user_filters %}
  <main role="main" class="container">
    <div class="row">
      <!-- Левый вспомогательный блок -->
      <div class="col-md-3 mb-3 mt-1">
        <div class="card">
          <div class="card-body">
            <ul class="list-group list-group-flush">
              <li class="list-group-item">
                <div class="h3">
                  Об авторе
                </div> 
              </li>
              <li class="list-group-item">
                <div class="h6 text-muted">
                  Полезный короткий текст
                </div>
              </li>
            </ul>                                               
          </div>                    
        </div>                
      </div>
      <!-- Тело страницы -->
      <div class="col-md-9">
        <div class="card-body">                    
          <div class="card-text">
            <p>Текст страницы "Об авторе"</p>
          </div>                    
        </div>                
      </div>            
    </div>        
  </main>
{% endblock %}

yatube/about/templates/about/tech.html
{% extends "base.html" %}
{% block title %}Технологии{% endblock %}
{% block content %}
{% load user_filters %}
  <main role="main" class="container">
    <div class="row">
      <!-- Левый вспомогательный блок -->
      <div class="col-md-3 mb-3 mt-1">
        <div class="card">
          <div class="card-body">
            <ul class="list-group list-group-flush">
              <li class="list-group-item">
                <div class="h3">
                    Технологии
                </div> 
              </li>
              <li class="list-group-item">
                <div class="h6 text-muted">
                  Питончик
                </div>
              </li>
            </ul>                                               
          </div>                    
        </div>                
      </div>
      <!-- Тело страницы -->
      <div class="col-md-9">
        <div class="card-body">                    
          <div class="card-text">
            <p>На этой странице можно рассказать, какие программные инструменты вы применили для создания этого сайта,
               какие навыки вам помогли, с чем вы хорошо разобрались, а с чем — не очень. Картинки и нестандартные подходы 
               приветствуются: эта страница может получиться очень интересной.</p>
          </div>                    
        </div>                
      </div>            
    </div>        
  </main>
{% endblock %}

yatube/posts/templates/group.html
{% extends "base.html" %}
{% block title %}Записи сообщества {{ group.title }}{% endblock %}
{% block header %}{{ group.title }}{% endblock %}
{% block content %}
    <p>
        {{ group.description }}
    </p>
    {% for post in page %}
        <h3>
            Автор: {{ post.author.get_full_name }}, Дата публикации: {{ post.pub_date|date:"d M Y" }}
        </h3>
        <p>
            {{ post.text|linebreaksbr }}
        </p>
        <hr>
    {% endfor %}
    {% include "include/paginator.html" %}
{% endblock %}

yatube/posts/templates/include/post_item.html
<div class="card mb-3 mt-1 shadow-sm">
    <div class="card-body">
        <p class="card-text">
            <a href="{% url 'profile' post.author.username %}"><strong class="d-block text-gray-dark">@{{ post.author }}</strong></a>
            {{ post.text|linebreaksbr }}
        </p>
        <div class="d-flex justify-content-between align-items-center">
            <div class="btn-group ">
                <a class="btn btn-sm text-muted" href="{% url 'post' post.author.username post.id %}" role="button">Добавить комментарий</a>
                {% if user == post.author %}
                    <a class="btn btn-sm btn-info" href="{% url 'post_edit' post.author.username post.id %}" role="button">Редактировать</a>
                {% endif %}
            </div>
            <small class="text-muted">{{ post.pub_date }}</small>
        </div>
    </div>
</div>

yatube/posts/templates/include/user_info.html
<div class="col-md-3 mb-3 mt-1">
    <div class="card">
      <div class="card-body">
        <div class="h2">{{ author.get_full_name }}</div>
          <div class="h3 text-muted"> @{{ author.username}} </div>
      </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            <div class="h6 text-muted"> Подписчиков: XXX <br /> Подписан: XXX </div>
          </li>
          <li class="list-group-item">
            <div class="h6 text-muted"> Количество записей: {{ author.posts.count }} </div>
          </li>
        </ul>
    </div>
  </div>

yatube/posts/templates/index.html
{% extends "base.html" %}
{% block title %}Последние обновления на сайте{% endblock %}
{% block header %}Последние обновления на сайте{% endblock %}
{% block content %}

    {% for post in page %}
    <h3>
        Автор: {{ post.author.get_full_name }}, Дата публикации: {{ post.pub_date|date:"d M Y" }}
    </h3>
    <p>
        {{ post.text|linebreaksbr }}
    </p>
    {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include "include/paginator.html" %}

{% endblock %}

yatube/posts/templates/newpost.html
{% extends "base.html" %}
{% block title %}Создание новой записи{% endblock %}
{% block header %}{{ group.title }}{% endblock %}
{% block content %}
{% load user_filters %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
      {%if post  %}  
        <h1>Редактировать пост</h1>
      {%else%} 
        <h1>Создание нового поста</h1>
      {%endif%}          
    <form method="post" 
        {%if post %} action="{% url 'post_edit' post.author.username post.id  %}"
        {%else%}  action="{% url 'new_post' %}"
        {%endif%}>
        {% csrf_token %}

        {% for field in form %}
            <div class="form-group row" aria-required={% if field.field.required %}"true"{% else %}"false"{% endif %}>
                <label for="{{ field.id_for_label }}" class="col-md-2 col-form-label text-md-right">{{ field.label }}{% if field.field.required %}<span class="required">*</span>{% endif %}</label>
                <div class="col-md-8">

                    {# подключаем фильтр и указываем класс #}
                    {{ field | addclass:"form-control"}}

                    {% if field.help_text %}
                    <small id="{{ field.id_for_label }}-help" class="form-text text-muted">{{ field.help_text|safe }}</small>
                    {% endif %}
                </div>                
            </div>
        {% endfor %}
        <div class="col-md-8 offset-md-2">              
            <button type="submit" class="btn btn-primary">
                {%if post  %}  
                  Сохранить
                {%else%} 
                  Добавить
                {%endif%}    
            </button>
        </div>
    </form> 
</div>
</div>
{% endblock %}

yatube/posts/templates/post.html
{% extends "base.html" %}
{% block title %}{{ user.user.get_full_name }}{% endblock %}
{% block content %}
<main role="main" class="container">
  <div class="row">
    {% include "include/user_info.html" with author=author %}
    <div class="col-md-9">
      {% include "include/post_item.html" with post=post %}
    </div>
  </div>
</main>
{% endblock %}

yatube/posts/templates/profile.html
{% extends "base.html" %}
{% block title %}{{ user.user.get_full_name }}{% endblock %}
{% block content %}
<main role="main" class="container">
  <div class="row">
    {% include "include/user_info.html" with author=author %}
    <div class="col-md-9">
      {% for post in page %}
      {% include "include/post_item.html" with post=post %}
      {%endfor%}
      {% include "include/paginator.html" %}
    </div>
  </div>
</main>
{% endblock %}

yatube/templates/base.html
<!doctype html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}The Last Social Media You'll Ever Need{% endblock %} | Yatube</title>
    <!-- Загрузка статики -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}">
    <script src="{% static 'jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}"></script>
</head>

<body>
    {% include 'include/nav.html' %}
    <main>
        <div class="container">
            <h1>
                {% block header %}The Last Social Media You'll Ever Need{% endblock %}
            </h1>
            {% block content %}
            <!-- Содержимое страницы -->
            {% endblock %}
        </div>
    </main>
    {% include 'include/footer.html' %}
</body>

</html>

yatube/templates/include/footer.html
<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <p class="m-0 text-dark text-center ">
        <a href="{% url 'about:author' %}">Об авторе</a>
        <a href="{% url 'about:tech' %}">Технологии</a>
    </p>
    <p class="m-0 text-dark text-center ">Социальная сеть <span style="color:red">Ya</span>tube © {{ YEAR }}, все права защищены.</p>
  </footer> 

yatube/templates/include/nav.html
<nav class="navbar navbar-light" style="background-color: #e3f2fd;">
    <a class="navbar-brand" href="/"><span style="color:red">Ya</span>tube</a>
    <nav class="my-2 my-md-0 mr-md-3">
        {% if user.is_authenticated %}
        Пользователь: {{ user.username }}.
        <a class="p-2 text-dark" href="{% url 'new_post' %}">Новый пост</a>
        <a class="p-2 text-dark" href="{% url 'password_change' %}">Изменить пароль</a>
        <a class="p-2 text-dark" href="{% url 'logout' %}">Выйти</a>
        {% else %}
        <a class="p-2 text-dark" href="{% url 'login' %}">Войти</a> |
        <a class="p-2 text-dark" href="{% url 'signup' %}">Регистрация</a>
        {% endif %}
    </nav>
</nav> 

yatube/templates/include/paginator.html
{# Отрисовываем навигацию паджинатора только если есть и другие страницы #}
{% if page.has_other_pages %}
<nav>
  <ul class="pagination">
    {% if page.has_previous %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page.previous_page_number }}">&laquo; Предыдущая</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <span class="page-link">&laquo; Предыдущая</span>
    </li>
    {% endif %}
    {% for i in page.paginator.page_range %}
    {% if page.number == i %}
    <li class="page-item active">
      <span class="page-link">{{ i }}
        <span class="sr-only">(текущая)</span>
      </span>
    </li>
    {% else %}
    <li class="page-item">
      <a class="page-link" href="?page={{ i }}">{{ i }}</a>
    </li>
    {% endif %}
    {% endfor %}
    {% if page.has_next %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page.next_page_number }}">Следующая &raquo;</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <span class="page-link">Следующая &raquo;</span>
    </li>
    {% endif %}
  </ul>
</nav>
{% endif %}

yatube/users/templates/signup.html
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
{# загружаем фильтр #}
{% load user_filters %}

<div class="row justify-content-center">
    <div class="col-md-8 p-5">
        <div class="card">
            <div class="card-header">Зарегистрироваться</div>
            <div class="card-body">
                
              {% for error in form.errors %}
                  <div class="alert alert-danger" role="alert">
                      {{ error|escape }}
                  </div>
                {% endfor %}

                <form method="post" action="{% url 'signup' %}">
                    {% csrf_token %}

                    {% for field in form %}
                        <div class="form-group row" aria-required={% if field.field.required %}"true"{% else %}"false"{% endif %}>
                                <label for="{{ field.id_for_label }}" class="col-md-4 col-form-label text-md-right">{{ field.label }}{% if field.field.required %}<span class="required">*</span>{% endif %}</label>
                                <div class="col-md-6">

                                    {# подключаем фильтр и указываем класс #}
                                    {{ field|addclass:"form-control" }}

                                    {% if field.help_text %}
                                    <small id="{{ field.id_for_label }}-help" class="form-text text-muted">{{ field.help_text|safe }}</small>
                                    {% endif %}
                                </div>                
                        </div>
                    {% endfor %}

                    <div class="col-md-6 offset-md-4">              
                            <button type="submit" class="btn btn-primary">
                                Зарегистрироваться
                            </button>
                    </div>
                </form>
            </div> <!-- card body -->
        </div> <!-- card -->
    </div> <!-- col -->
</div> <!-- row -->

{% endblock %}